FROM oven/bun:alpine AS base

FROM node:21-bookworm AS node_with_bun
RUN npm install -g bun

# Install dependencies
FROM node_with_bun AS builder
WORKDIR /frontend

COPY . .
RUN bun install && bun run build


EXPOSE 3000
ENV PORT 3000

CMD ["bun", "run", "start"]